name: 'e2e'

on:
  push:
    branches:
      - main # Adjust the branch name if needed

jobs:
  test-e2e:
    name: Run E2E tests
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22' # Use LTS version

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test tests/home.spec.ts

      - name: Generate Allure report
        run: npx allure generate allure-results --clean -o allure-report

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: TestResults
          path: |
            test-results
            allure-results
            allure-report
